network:
  actor_hidden_sizes: [256, 256]
  sac_critic_hidden_sizes: [256, 256]
  scale_lb: 0.1
  default_policy_scale: 1.0
solver:
  taylor_green: True
  swimmer_speed: 0.3
  alignment_timescale: 1.0

# Taylor_green parameters 
env: 
  # Flow parameters
  _SWIMMER_SPEED: 0.3
  _ALIGNMENT_TIMESCALE: 1.0

  # Constants for environment
  _FLOW_SPEED:  1.0
  _SIMULATION_TIMESTEP:  0.01
  _TIMESTEP:  0.01
  _DIFFUSIVITY_ROTATIONAL:  0.0001
  _DIFFUSIVITY_TRANSLATIONAL:  0.001
  _MIN_FLOW_SPEED_THRESHOLD:  1e-8