network:
  actor_hidden_sizes: [256, 256]
  sac_critic_hidden_sizes: [256, 256]
  scale_lb: 0.1
  default_policy_scale: 1.0
solver:
  taylor_green: True
env:
# Taylor_green parameters
  dt: 0.01
  swimmer_speed: 0.3
  flow_speed: 1.0
  alignment_timescale: 1.0
  diffusivity_rotational: 0.0001
  diffusivity_translational: 0.001
  max_episode_steps:  10000
  action_type: "continuous"
